version: '3.8'

services:
    db-master:
        build:
            context: ./master
            dockerfile: Dockerfile
        container_name: mysql_master
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - mysqldata_master:/var/lib/mysqldata_master
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: "Asia/Jakarta"
        networks:
            database_net:
                ipv4_address: 10.0.1.10
        healthcheck:
            test: "mysqladmin ping -h 10.0.1.10"
            interval: 2s
            retries: 20
    db-slave:
        build:
            context: ./slave
            dockerfile: Dockerfile
        container_name: mysql_slave
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            # - ./slave/start-replication.sh:/docker-entrypoint-initdb.d/start-replication.sh
            - mysqldata_slave:/var/lib/mysqldata_slave
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: "Asia/Jakarta"
        networks:
            database_net:
                ipv4_address: 10.0.1.11
        healthcheck:
            test: "mysqladmin ping -h 10.0.1.11"
            interval: 2s
            retries: 20

networks:
    database_net:
        ipam:
            config:
                - subnet: 10.0.1.0/24
        external: false

volumes:
    mysqldata_master:
    mysqldata_slave:
