global:
  resolve_timeout: 3m

route:
  receiver: 'Fenrir'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 3m
  routes:
    - match:
        severity: warning
      receiver: Fenrir

templates:
  - 'discord.tmpl'

receivers:
  - name: 'Fenrir'
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/
        message: '{{ template "discord_message" . }}'
        # parse_mode: ''