version: '3.8'

services:
    db-master:
        build:
            context: ./master
            dockerfile: Dockerfile
        container_name: mariadb-master
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - mariadbdata_master:/var/lib/mariadbdata_master
            - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MARIADB_ROOT_PASSWORD: M54if0IhQgc1
            MARIADB_DATABASE: master
            MARIADB_USER: db_user
            MARIADB_PASSWORD: M64if0IhQgc1
            TZ: "Asia/Jakarta"
        networks:
            mariadb_net:
                ipv4_address: 10.0.2.88
        healthcheck:
            test: "mysqladmin ping -u  db_user -pM64if0IhQgc1"
            interval: 2s
            retries: 20
    db-slave:
        build:
            context: ./slave
            dockerfile: Dockerfile
        container_name: mariadb-slave
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - ./slave/replication.sh:/docker-entrypoint-initdb.d/start-replication.sh
            - ./slave/init.sql:/docker-entrypoint-initdb.d/init.sql
            - mariadbdata_slave:/var/lib/mariadbdata_slave
        environment:
            MARIADB_ROOT_PASSWORD: M54if0IhQgc1
            MARIADB_USER:  db_user
            MARIADB_PASSWORD: M64if0IhQgc1
            TZ: "Asia/Jakarta"
        networks:
            mariadb_net:
                ipv4_address: 10.0.2.99
        healthcheck:
            test: "mysqladmin ping -u  db_user -pM64if0IhQgc1"
            interval: 2s
            retries: 20

networks:
    mariadb_net:
        ipam:
            config:
                - subnet: 10.0.2.0/24
        external: false

volumes:
    mariadbdata_master:
    mariadbdata_slave: