global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert-rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '10.104.0.2:9093'
    scheme: http
    timeout: 10s

scrape_configs:

- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - '10.104.0.2:9100'

  relabel_configs:
  - source_labels: [__address__]
    regex: 10.104.0.2:9100
    target_label: server
    replacement: server1